"""Use Playwright to visit YouTube (real browser → no bot check), save fresh
cookies including any visitor_data/PO tokens, then hand them to yt-dlp."""
import asyncio, json, time, sys, subprocess
from pathlib import Path
from playwright.async_api import async_playwright

YT_ID = sys.argv[1] if len(sys.argv) > 1 else "o169wQ_4-1w"
OUT = Path("/tmp/yt_via_browser")
OUT.mkdir(exist_ok=True)
COOKIES_TXT = OUT / "cookies.txt"


def cookies_to_netscape(cookies):
    """Convert Playwright cookies to Netscape cookies.txt format that yt-dlp reads."""
    lines = ["# Netscape HTTP Cookie File", "# Generated by playwright probe", ""]
    for c in cookies:
        domain = c.get("domain", "")
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        expires = int(c.get("expires", 0)) if c.get("expires", -1) > 0 else 0
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
    return "\n".join(lines) + "\n"


async def main():
    t0 = time.time()
    async with async_playwright() as p:
        browser = await p.chromium.launch(
            headless=True,
            args=["--no-sandbox", "--disable-dev-shm-usage"],
        )
        ctx = await browser.new_context(
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36",
            viewport={"width": 1280, "height": 800},
        )
        page = await ctx.new_page()
        print(f"[{time.time()-t0:.2f}s] visiting YouTube watch page…")
        await page.goto(f"https://www.youtube.com/watch?v={YT_ID}",
                        wait_until="domcontentloaded", timeout=30000)
        # Let the page settle so cookies + visitor_data are set
        await asyncio.sleep(4)
        print(f"[{time.time()-t0:.2f}s] page loaded")

        # Check for consent / bot interstitial
        url = page.url
        print(f"   final url: {url[:120]}")
        title = await page.title()
        print(f"   title: {title}")
        # See if we got a real video page (vs a "before you continue" / sign-in wall)
        has_player = await page.evaluate("!!document.getElementById('movie_player') || !!document.querySelector('ytd-player')")
        print(f"   player present: {has_player}")

        cookies = await ctx.cookies("https://www.youtube.com/")
        print(f"   {len(cookies)} cookies for youtube.com")
        # Show key cookie names
        names = sorted(c["name"] for c in cookies)
        print(f"   cookie names: {names[:20]}")

        COOKIES_TXT.write_text(cookies_to_netscape(cookies))
        await browser.close()
        print(f"[{time.time()-t0:.2f}s] cookies saved → {COOKIES_TXT}")

    # Now run yt-dlp with these cookies — first just metadata
    print(f"\n=== yt-dlp -j --cookies (metadata only) ===")
    t1 = time.time()
    cp_meta = subprocess.run(
        ["/opt/playly-yt-worker/venv/bin/yt-dlp",
         "--cookies", str(COOKIES_TXT),
         "--extractor-args", "youtube:player_client=web,android",
         "-j", "--no-warnings", "--socket-timeout", "30",
         f"https://www.youtube.com/watch?v={YT_ID}"],
        capture_output=True, text=True, timeout=60)
    print(f"   exit={cp_meta.returncode} ({time.time()-t1:.2f}s)")
    if cp_meta.returncode == 0:
        info = json.loads(cp_meta.stdout)
        print(f"   ✅ title: {info.get('title','')[:80]}")
        print(f"   duration: {info.get('duration')}s")
    else:
        print(f"   ❌ error: {cp_meta.stderr[:400]}")
        return

    # Real download to MP3
    print(f"\n=== yt-dlp full download (mp3 192) ===")
    t2 = time.time()
    out_path = OUT / f"{YT_ID}.%(ext)s"
    cp_dl = subprocess.run(
        ["/opt/playly-yt-worker/venv/bin/yt-dlp",
         "--cookies", str(COOKIES_TXT),
         "--extractor-args", "youtube:player_client=web,android",
         "-x", "--audio-format", "mp3", "--audio-quality", "192",
         "--no-warnings", "--socket-timeout", "30",
         "-o", str(out_path),
         f"https://www.youtube.com/watch?v={YT_ID}"],
        capture_output=True, text=True, timeout=180)
    elapsed = time.time() - t2
    print(f"   exit={cp_dl.returncode} ({elapsed:.2f}s)")
    if cp_dl.returncode == 0:
        mp3 = next(OUT.glob(f"{YT_ID}.mp3"), None)
        if mp3:
            print(f"   ✅ {mp3.name} — {mp3.stat().st_size:,} bytes")
            probe = subprocess.run(["ffprobe", "-v", "error",
                "-show_entries", "format=duration,bit_rate",
                "-of", "default=noprint_wrappers=1", str(mp3)],
                capture_output=True, text=True)
            print(f"   ffprobe: {probe.stdout.strip()}")
            print(f"\n>>> TOTAL END-TO-END (browser cookies → yt-dlp → mp3): {time.time()-t0:.2f}s <<<")
    else:
        print(f"   ❌ stderr (tail): {cp_dl.stderr[-600:]}")


asyncio.run(main())
